
services:
  backend:
    build: ./car-rental-backend
    container_name: mern-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    
    networks:
      - mern-network

  frontend:
    build: ./car-rental-frontend
    container_name: mern-frontend
    ports:
      - "8000:80"
    depends_on:
      - backend
    networks:
      - mern-network



networks:
  mern-network:
    driver: bridge
