name: Deploy MERN App with Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker
        run: |
          curl -fsSL https://get.docker.com | sh
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Build and run Docker Compose
        run: |
          docker compose up -d --build

      - name: Check running containers
        run: |
          docker ps
