name: Deploy MERN App with Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker and Docker Compose
        run: |
          curl -fsSL https://get.docker.com | sh
          sudo systemctl start docker
          sudo systemctl enable docker
          sudo apt-get update
          sudo apt-get install docker-compose-plugin -y

      - name: Create .env file from GitHub Secrets
        run: |
          touch .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          # Add other secrets if needed

      - name: Build and run Docker Compose
        run: |
          docker compose up -d --build

      - name: Check running containers
        run: |
          docker ps

      - name: Test if the frontend is running
        run: |
          curl http://localhost:8000  # Frontend is expected to run on port 8000

      - name: Test backend health check
        run: |
          curl http://localhost:5000/api/health  # Backend health check endpoint on port 5000

      - name: Cleanup - Remove .env for security
        run: |
          rm -f .env
