name: Deploy MERN App with Docker

on:
  push:
    branches:
      - main  # or master, depending on your repo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build and run Docker Compose
        run: |
          docker-compose up -d --build

      - name: Check running containers
        run: |
          docker ps
